### ISSUE TITLE
不知道老师有没有研究过Ipic等一些辅助工具

### ISSUE THREAD

**Issue by EsqerYasen** [xiaolai/apple-computer-literacy#1]
功能是把markdown文件里面的本地图片上传到免费空间（也有会员），这样目录结果看起来很干净，图片直接从网上下载，速度也很快。只有一个.md文件就可以。

**Comment by EsqerYasen** [comment]
用typora写完文档的时候直接拖进图片，然后写完以后右键上传图片就可以，特别方便。

**Comment by xiaolai** [comment]
关键是那些免费空间不稳定，过几年就都不见了……

**Comment by EsqerYasen** [comment]
> 关键是那些免费空间不稳定，过几年就都不见了……

好的， 我目前用了一段时间，还算比较稳定。 老师考虑真周到。
