### ISSUE TITLE
备份问题

### ISSUE THREAD

**Issue by sxuya** [xiaolai/apple-computer-literacy#3]
主要是 typaro 软件的使用。

功能确实喜欢，由于老师介绍，一直在使用了。but，因为它是本地程序、文件也是本地存储，但是这样就只能在一台设备编辑了。

假设：在外只有手机想要改一下某个地方？电脑丢了？用其他电脑临时编辑一下？……

老师是如何实现云备份/云存储？直接使用 iCloud 备份功能么？

**Comment by liusanhong** [comment]
> 主要是 typaro 软件的使用。
> 
> 功能确实喜欢，由于老师介绍，一直在使用了。but，因为它是本地程序、文件也是本地存储，但是这样就只能在一台设备编辑了。
> 
> 假设：在外只有手机想要改一下某个地方？电脑丢了？用其他电脑临时编辑一下？……
> 
> 老师是如何实现云备份/云存储？直接使用 iCloud 备份功能么？

你丢掉github不就可以了么

**Comment by sxuya** [comment]
又研究了几天，最后使用的方法是 github + 坚果云。
- 创建坚果云的同步文件夹。
- 在上面的文件夹里面进行 md 文件的创建，因此可以自动备份。
- 再把第一步的文件夹做成 github 的仓库。

这样，github 可以用来进行版本管理，坚果云可以作跨设备的编写，每次回到电脑上，直接 push 到 github 就一步版本管理了。

**Comment by EsqerYasen** [comment]
@sxuya  既然已经解决了 ， issue 可以关了 看着难受 😄。

**Comment by sxuya** [comment]
> @sxuya 既然已经解决了 ， issue 可以关了 看着难受 😄。

github 还在摸索使用，有些使用规范不是很清楚。多谢提醒。
